# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images: {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# Site settings
title: "Sociology 341 Library Session"
# description and keywords for meta tags
description: "Learn how to search in STS journals and library databases"
keywords: "library instruction, search strategies, citation chaining"

# author settings for cc-by
author: Jylisa Doney
pub_year: 2018
github_username: jylisadoney

# add the full url for the github repository
repo: "https://github.com/jylisadoney/soc-341"

# site urls
# add the url for the domain,
# on gh-pages: https://username.github.io 
url: https://jylisadoney.github.io
# add subsection of the domain,
# on gh-pages this is the name of the repository
baseurl: /soc-341

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
